# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-25 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191122_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='book',
            name='dianzan',
            field=models.IntegerField(default=100),
        ),
    ]
