# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-27 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191125_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.CharField(default='男', max_length=16),
        ),
    ]
