# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-04 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_author_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='dianzan',
        ),
    ]
